# Generated by Django 4.0.2 on 2022-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='color_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Color code'),
        ),
    ]
