# Generated by Django 4.0.3 on 2022-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
        ('temp_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='opening_days',
            field=models.ManyToManyField(blank=True, related_name='temp_shop_opening_days', to='auth_shop.authshopdays', verbose_name='Opening days'),
        ),
    ]
