# Generated by Django 4.0.2 on 2022-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_shop', '0003_alter_tempshop_font_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='font_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Font name'),
        ),
    ]
