# Generated by Django 4.0.2 on 2022-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
        ('temp_shop', '0004_alter_tempshop_font_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='opening_days',
            field=models.ManyToManyField(blank=True, related_name='temp_shop_opening_days', to='auth_shop.Days', verbose_name='Opening days'),
        ),
    ]
