# Generated by Django 4.0.5 on 2022-06-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=1000, verbose_name='English name')),
                ('name_fr', models.CharField(blank=True, max_length=1000, verbose_name='French name')),
                ('name_ar', models.CharField(blank=True, max_length=1000, verbose_name='Arabic name')),
                ('overpass_turbo_id', models.BigIntegerField(blank=True, null=True, verbose_name='Overpass turbo ID')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('type', models.CharField(choices=[('country', 'Country'), ('area', 'Area')], default='country', max_length=20, verbose_name='Type of country')),
                ('currency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Currency')),
                ('currency_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Currency AR')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='places.country', verbose_name='Belong')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=1000, verbose_name='English name')),
                ('name_fr', models.CharField(blank=True, max_length=1000, verbose_name='French name')),
                ('name_ar', models.CharField(blank=True, max_length=1000, verbose_name='Arabic name')),
                ('overpass_turbo_id', models.BigIntegerField(blank=True, null=True, verbose_name='Overpass turbo ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='places.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('pk',),
            },
        ),
    ]
