# Generated by Django 4.0.5 on 2022-06-07 09:55

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('gender', models.CharField(blank=True, choices=[('', 'Unset'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Phone number')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Avatar')),
                ('avatar_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Thumb Avatar')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_enclosed', models.BooleanField(default=False, verbose_name='Compte clôturer ?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('activation_code', models.IntegerField(blank=True, null=True, verbose_name='Account Activation Code')),
                ('password_reset_code', models.IntegerField(blank=True, null=True, verbose_name='Password Reset Code')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_custom_user', to='places.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'type': 'country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_custom_user', to='places.country', verbose_name='Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('date_joined',),
            },
        ),
        migrations.CreateModel(
            name='DeletedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('reason_choice', models.CharField(blank=True, choices=[('', 'Unset'), ('A', 'Je cesse mon activité'), ('B', 'Je cesse mon activité 2')], default='', max_length=1, null=True)),
                ('typed_reason', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Deleted Accounts',
                'verbose_name_plural': 'Deleted Accounts',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('zip_code', models.PositiveIntegerField(verbose_name='Zip code')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_user_address', to='places.city', verbose_name='City')),
                ('country', models.ForeignKey(limit_choices_to={'type': 'country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_user_address', to='places.country', verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_address', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
        migrations.CreateModel(
            name='ReportedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('1', 'Reason 1'), ('2', 'Reason 2'), ('3', 'Reason 3'), ('4', 'Reason 4')], default='1', max_length=1, verbose_name='Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_sender', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Reported user')),
            ],
            options={
                'verbose_name': 'Reported User',
                'verbose_name_plural': 'Reported Users',
            },
        ),
        migrations.CreateModel(
            name='EnclosedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_choice', models.CharField(blank=True, choices=[('', 'Unset'), ('A', 'Je cesse mon activité'), ('B', 'Je cesse mon activité 2')], default='', max_length=1, null=True)),
                ('typed_reason', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_enclosed_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Enclosed Account',
                'verbose_name_plural': 'Enclosed Accounts',
            },
        ),
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_sender', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Blocked user')),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'unique_together': {('user', 'user_blocked')},
            },
        ),
    ]
