# Generated by Django 4.0.2 on 2022-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Account Activation Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Password Reset Code'),
        ),
    ]
