# Generated by Django 4.0.3 on 2022-03-10 14:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Thumb Avatar'),
        ),
    ]
