# Generated by Django 4.0.5 on 2022-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_id_activation',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Task ID activation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='task_id_password_reset',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Task ID password reset'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
