# Generated by Django 4.1 on 2022-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_task_id_activation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City'),
        ),
    ]
