# Generated by Django 4.0.3 on 2022-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1, null=True),
        ),
    ]
