# Generated by Django 4.0.2 on 2022-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('', 'Unset'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
