# Generated by Django 4.0.3 on 2022-03-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('1', 'Reason 1'), ('2', 'Reason 2'), ('3', 'Reason 3'), ('4', 'Reason 4')], default='1', max_length=1, verbose_name='Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_sender', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Reported user')),
            ],
            options={
                'verbose_name_plural': 'Reported items',
            },
        ),
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_sender', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Blocked user')),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'unique_together': {('user', 'user_blocked')},
            },
        ),
    ]
