# Generated by Django 4.1 on 2022-10-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_article', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Nombre d'article")),
                ('prix_ht', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Prix HT')),
                ('prix_ttc', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Prix TTC')),
                ('prix_unitaire', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Prix d'article /u")),
                ('pourcentage', models.IntegerField(blank=True, default=None, null=True, verbose_name='Pourcentage')),
            ],
            options={
                'verbose_name': 'Available subscription',
                'verbose_name_plural': 'Available subscriptions',
                'ordering': ('-pk',),
            },
        ),
    ]
