# Generated by Django 4.1 on 2022-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_promocodes_requestedsubscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='facture',
            field=models.FilePathField(path='media/files/d8ceafd2-192a-41e3-a63c-8a280be3b76a.pdf', verbose_name='Facture'),
        ),
    ]
