# Generated by Django 4.1 on 2022-10-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('subscription', '0003_promocodes_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='-% price or nbr (depend on type)'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='adresse',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='code_postal',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_requested_subscription', to='places.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='ice',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='ICE'),
        ),
        migrations.AlterField(
            model_name='requestedsubscriptions',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='facture',
            field=models.FilePathField(blank=True, default=None, null=True, path='media/files/87f437a6-285d-4f67-99ce-b56bdaa73ce1.pdf', verbose_name='Facture'),
        ),
    ]
