# Generated by Django 4.1.3 on 2022-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_requestedsubscriptions_facture_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedsubscriptions',
            name='remaining_to_pay',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Remaining to pay'),
        ),
    ]
