# Generated by Django 4.1.3 on 2022-12-06 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_requestedsubscriptions_remaining_to_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexedarticles',
            options={'ordering': ('-created_date', '-updated_date'), 'verbose_name': 'Indexed article', 'verbose_name_plural': 'Indexed articles'},
        ),
        migrations.AddField(
            model_name='indexedarticles',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexedarticles',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
