# Generated by Django 4.1.3 on 2022-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_indexedarticles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexedarticles',
            options={'ordering': ('-updated_date', '-created_date'), 'verbose_name': 'Indexed article', 'verbose_name_plural': 'Indexed articles'},
        ),
        migrations.AlterField(
            model_name='indexedarticles',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='indexedarticles',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date mis à jour'),
        ),
    ]
