# Generated by Django 4.1.3 on 2022-12-06 12:51

from django.db import migrations, models
import django.db.models.deletion
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_tempoffers_auth_shop_and_more'),
        ('subscription', '0014_alter_indexedarticles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedarticles',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_offer', to='offers.offers', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='indexedarticles',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_indexed_articles', to='subscription.subscribedusers', verbose_name='Boutique Abonnée'),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='expiration_date',
            field=models.DateTimeField(default=subscription.models.get_expiration_date, verbose_name="Date d'expiration Abo"),
        ),
    ]
