# Generated by Django 4.1.3 on 2022-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_indexedarticles_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedarticles',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('I', 'Indexed'), ('U', 'Updated')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
