# Generated by Django 4.1.5 on 2023-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_indexedarticles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedarticles',
            name='email_informed',
            field=models.BooleanField(default=False, verbose_name='Email informed'),
        ),
    ]
