# Generated by Django 4.1.5 on 2023-01-05 21:19

from django.db import migrations, models
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_alter_indexedarticles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='expiration_date',
            field=models.DateTimeField(default=subscription.models.get_expiration_date, verbose_name='Date expiration Abo'),
        ),
    ]
