# Generated by Django 4.1.5 on 2023-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_alter_subscribedusers_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedSignIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=30, verbose_name='Prénom')),
                ('phone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('instagram_page', models.SlugField(blank=True, default=None, max_length=255, null=True, verbose_name='Lien de la page (instagram)')),
                ('horaire', models.CharField(choices=[('M', '9-12'), ('A', '13-16')], default='M', max_length=1, verbose_name='Horaire')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Requested SignIn',
                'verbose_name_plural': 'Requested SignIns',
                'ordering': ('-pk',),
            },
        ),
    ]
