# Generated by Django 4.1.5 on 2023-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_requestedsignins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedsignins',
            name='horaire',
            field=models.CharField(choices=[('M', '9-12'), ('A', '13-16'), ('S', '17-18')], default='M', max_length=1, verbose_name='Horaire'),
        ),
    ]
