# Generated by Django 4.1.6 on 2023-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_alter_requestedsignins_instagram_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedsignins',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='requestedsignins',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='requestedsignins',
            name='last_name',
        ),
        migrations.AddField(
            model_name='requestedsignins',
            name='creneau',
            field=models.CharField(choices=[('M', '9-12'), ('A', '13-16'), ('S', '17-18')], default='M', max_length=1, verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='requestedsignins',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='requestedsignins',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nom & prénom'),
        ),
        migrations.AddField(
            model_name='requestedsignins',
            name='secteur',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='requestedsignins',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Téléphone'),
        ),
    ]
