# Generated by Django 4.1.6 on 2023-02-10 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0023_remove_requestedsignins_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedsignins',
            name='line_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Line number'),
        ),
        migrations.AddField(
            model_name='requestedsignins',
            name='unique_number',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Unique number'),
        ),
    ]
