# Generated by Django 4.1.6 on 2023-02-10 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0024_requestedsignins_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedsignins',
            name='creneau',
            field=models.CharField(choices=[('M', '9h-12h'), ('A', '13h-16h'), ('S', '17h-18h')], default='M', max_length=1, verbose_name='Créneau'),
        ),
        migrations.AlterField(
            model_name='requestedsignins',
            name='unique_number',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Unique number'),
        ),
    ]
