# Generated by Django 4.1.6 on 2023-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0025_alter_requestedsignins_creneau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedsignins',
            name='unique_number',
            field=models.CharField(default='c3ce77a7-cb58-4bc0-a961-9702b48b95c8', max_length=255, unique=True, verbose_name='Unique number'),
        ),
    ]
