# Generated by Django 4.1.6 on 2023-02-10 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0026_alter_requestedsignins_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedsignins',
            name='unique_number',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Unique number'),
        ),
    ]
