# Generated by Django 4.0.3 on 2022-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_delivery_delivery_days_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
    ]
