# Generated by Django 4.0.3 on 2022-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('offer', '0003_alter_products_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_city_1',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_city_2',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_city_3',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_days_1',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_days_2',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_days_3',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_price_1',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_price_2',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_price_3',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_city',
            field=models.ManyToManyField(related_name='delivery_city', to='places.city', verbose_name='Delivery City'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Days'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_price',
            field=models.FloatField(default=0.0, verbose_name='Delivery Price'),
        ),
    ]
