# Generated by Django 4.0.3 on 2022-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_remove_delivery_delivery_city_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Offer Tag',
                'verbose_name_plural': 'Offer Tags',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='creator_label',
            field=models.BooleanField(default=False, verbose_name='Creator label'),
        ),
        migrations.AddField(
            model_name='offers',
            name='made_in_label',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Made in'),
        ),
        migrations.AddField(
            model_name='offers',
            name='tags',
            field=models.ManyToManyField(related_name='offer_tags', to='offer.offertags', verbose_name='Offer Tags'),
        ),
    ]
