# Generated by Django 4.1.3 on 2022-12-05 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultseopage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tags'), default=None, size=None),
            preserve_default=False,
        ),
    ]
