# Generated by Django 4.1.3 on 2022-12-05 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0002_defaultseopage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultseopage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tags'), default=None, size=None),
        ),
    ]
