# Generated by Django 4.1.3 on 2022-12-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_indexedarticles_status'),
        ('seo_pages', '0004_defaultseopage_indexed_alter_defaultseopage_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSeoPageArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(related_name='default_seo_page_indexed_articles', to='subscription.indexedarticles', verbose_name='Articles')),
                ('seo_pages', models.ManyToManyField(related_name='default_seo_page_seo_pages', to='seo_pages.defaultseopage', verbose_name='Default seo pages')),
            ],
            options={
                'verbose_name': 'Default seo page Article',
                'verbose_name_plural': 'Default seo page Articles',
                'ordering': ('-pk',),
            },
        ),
    ]
