# Generated by Django 4.1.4 on 2022-12-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0005_defaultseopagearticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultseopagearticles',
            name='seo_pages',
        ),
        migrations.AddField(
            model_name='defaultseopagearticles',
            name='seo_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='default_seo_page_seo_page', to='seo_pages.defaultseopage',
                                    verbose_name='Default seo page'),
            preserve_default=False,
        ),
    ]
