# Generated by Django 4.1.4 on 2022-12-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0006_remove_defaultseopagearticles_seo_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultseopagearticles',
            name='seo_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_seo_page_seo_page', to='seo_pages.defaultseopage', verbose_name='Default seo page'),
        ),
    ]
