# Generated by Django 4.1.4 on 2022-12-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_authshop_facebook_link_and_more'),
        ('seo_pages', '0009_alter_defaultseopage_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coup_de_coeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authShop_coup_de_coeur', to='shop.authshop', unique=True, verbose_name='Boutique coup de coeur')),
                ('new_shops', models.ManyToManyField(blank=True, related_name='authShop_shops_joint', to='shop.authshop', verbose_name='New shops list')),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home page',
                'ordering': ('-pk',),
            },
        ),
    ]
