# Generated by Django 4.1.4 on 2022-12-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_authshop_facebook_link_and_more'),
        ('seo_pages', '0010_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='coup_de_coeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authShop_coup_de_coeur', to='shop.authshop', verbose_name='Boutique coup de coeur'),
        ),
    ]
