# Generated by Django 4.1.4 on 2022-12-24 13:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0011_alter_homepage_coup_de_coeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='coup_de_coeur_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Coup de coeur background color'),
        ),
    ]
