# Generated by Django 4.1.5 on 2023-01-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0012_homepage_coup_de_coeur_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultseopage',
            name='indexed',
            field=models.BooleanField(default=True, verbose_name='Page publier ?'),
        ),
    ]
