# Generated by Django 4.1.5 on 2023-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0013_alter_defaultseopage_indexed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultseopage',
            options={'ordering': ('-pk',), 'verbose_name': 'Seo page', 'verbose_name_plural': 'Seo pages'},
        ),
        migrations.RemoveField(
            model_name='defaultseopage',
            name='header',
        ),
        migrations.AddField(
            model_name='defaultseopage',
            name='h_one',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='defaultseopage',
            name='h_two',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='H2'),
        ),
        migrations.AlterField(
            model_name='defaultseopage',
            name='page_url',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Lien de la page (unique)'),
        ),
        migrations.AlterField(
            model_name='defaultseopage',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Titre de la page'),
        ),
    ]
