# Generated by Django 4.1.5 on 2023-01-14 04:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0015_alter_defaultseopage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultseopage',
            name='page_url',
            field=models.SlugField(blank=True, default=None, help_text='ex : ma-seo-page', max_length=255, null=True, unique=True, verbose_name='Lien de la page (unique)'),
        ),
        migrations.AlterField(
            model_name='defaultseopage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, help_text='ex : Divers,Beauté,Santé & Bien être...', max_length=100, null=True, verbose_name='Tags'), blank=True, default=None, help_text='Separated by comma ","', null=True, size=None),
        ),
    ]
