# Generated by Django 4.1.5 on 2023-01-18 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0017_alter_defaultseopage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultseopage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tags'), blank=True, default=None, help_text='ex : Divers,Beauté,Santé & Bien être... (Séparer par une virgule ",").', null=True, size=None),
        ),
    ]
