# Generated by Django 4.1.5 on 2023-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0018_alter_defaultseopage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultseopage',
            name='indexed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Dernière date d'indexation"),
        ),
    ]
