# Generated by Django 4.0.5 on 2022-06-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_for', models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], max_length=1, verbose_name='Rating for')),
                ('rating_note', models.PositiveIntegerField(default=1, verbose_name='Rating Note')),
                ('rating_body', models.CharField(default=None, max_length=255, verbose_name='Rating Body')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date')),
                ('user_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_user_receiver', to=settings.AUTH_USER_MODEL, verbose_name='User receiver')),
                ('user_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_user_sender', to=settings.AUTH_USER_MODEL, verbose_name='User sender')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ('-created_date',),
            },
        ),
    ]
