# Generated by Django 4.1 on 2022-08-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='rating_for',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user_receiver',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user_sender',
        ),
        migrations.AddField(
            model_name='ratings',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
