# Generated by Django 4.0.3 on 2022-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messagemodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='viewed_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
