# Generated by Django 4.0.3 on 2022-03-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_messagemodel_viewed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recevied_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='viewed_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Viewed Timestamp'),
        ),
    ]
