# Generated by Django 4.0.3 on 2022-03-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_messagemodel_body_alter_messagemodel_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_archived_conversation', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_archived_conversation', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Archived conversation',
                'verbose_name_plural': 'Archived conversations',
            },
        ),
    ]
