# Generated by Django 4.1.5 on 2023-01-09 17:18

import ckeditor.fields
import ckeditor_uploader.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Page url (unique)')),
                ('background_image', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Background image')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Titre de la page')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tags'), default=None, help_text='Separated by comma ","', size=None)),
                ('header', models.TextField(blank=True, default=None, null=True, verbose_name='Titre (h1)')),
                ('page_meta_description', models.TextField(blank=True, default=None, null=True, verbose_name='Meta description')),
                ('content', ckeditor.fields.RichTextField(blank=True, default=True, null=True, verbose_name='Page content')),
                ('indexed', models.BooleanField(default=True, verbose_name='Page publier ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Blog page',
                'verbose_name_plural': 'Blog pages',
                'ordering': ('-pk',),
            },
        ),
    ]
