# Generated by Django 4.1.5 on 2023-01-09 17:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=blog.models.get_blog_imgs_path, verbose_name='Background image'),
        ),
    ]
