# Generated by Django 4.1.5 on 2023-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background_image_alt',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="Description de l'image"),
        ),
    ]
