# Generated by Django 4.1.5 on 2023-01-18 07:42

import ckeditor_uploader.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='header',
        ),
        migrations.AddField(
            model_name='blog',
            name='h_one',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Le contenu de la page'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='page_url',
            field=models.SlugField(blank=True, default=None, help_text='ex : ma-blog-page', max_length=255, null=True, unique=True, verbose_name='Page url (unique)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tags'), blank=True, default=None, help_text='ex : Divers,Beauté,Santé & Bien être... (Séparer par une virgule ",").', null=True, size=None),
        ),
    ]
