# Generated by Django 4.1.5 on 2023-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_header_blog_h_one_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='indexed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Dernière date d'indexation"),
        ),
    ]
