# Generated by Django 4.0.5 on 2022-06-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='picture_4',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='picture_4_thumbnail',
        ),
        migrations.RemoveField(
            model_name='tempoffers',
            name='picture_4',
        ),
        migrations.RemoveField(
            model_name='tempoffers',
            name='picture_4_thumbnail',
        ),
    ]
