# Generated by Django 4.0.6 on 2022-07-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offers_picture_4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdelivery',
            old_name='temp_delivery_city',
            new_name='delivery_city',
        ),
        migrations.RenameField(
            model_name='tempdelivery',
            old_name='temp_delivery_days',
            new_name='delivery_days',
        ),
        migrations.RenameField(
            model_name='tempdelivery',
            old_name='temp_delivery_price',
            new_name='delivery_price',
        ),
        migrations.RenameField(
            model_name='tempdelivery',
            old_name='temp_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='tempoffers',
            old_name='temp_shop',
            new_name='auth_shop',
        ),
        migrations.RenameField(
            model_name='tempproducts',
            old_name='temp_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='tempservices',
            old_name='temp_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='tempsolder',
            old_name='temp_offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='tempsolder',
            old_name='temp_solder_type',
            new_name='solder_type',
        ),
        migrations.RenameField(
            model_name='tempsolder',
            old_name='temp_solder_value',
            new_name='solder_value',
        ),
    ]
