# Generated by Django 4.1 on 2022-08-23 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_temp_delivery_city_tempdelivery_delivery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product Latitude'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product Longitude'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Latitude'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Longitude'),
        ),
        migrations.AlterField(
            model_name='tempproducts',
            name='product_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product Latitude'),
        ),
        migrations.AlterField(
            model_name='tempproducts',
            name='product_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product Longitude'),
        ),
        migrations.AlterField(
            model_name='tempservices',
            name='service_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Latitude'),
        ),
        migrations.AlterField(
            model_name='tempservices',
            name='service_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Longitude'),
        ),
    ]
