# Generated by Django 4.1 on 2022-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_products_product_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='all_cities',
            field=models.BooleanField(default=False, verbose_name='Tout le maroc ?'),
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='all_cities',
            field=models.BooleanField(default=False, verbose_name='Tout le maroc ?'),
        ),
    ]
