# Generated by Django 4.1 on 2022-09-07 17:11

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_delivery_all_cities_tempdelivery_all_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='picture_4',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=offers.models.get_shop_offers_path, verbose_name='Picture 4'),
        ),
        migrations.AddField(
            model_name='offers',
            name='picture_4_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=offers.models.get_shop_offers_path, verbose_name='Picture 4 thumbnail'),
        ),
        migrations.AddField(
            model_name='tempoffers',
            name='picture_4',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=offers.models.get_shop_offers_path, verbose_name='Picture 4'),
        ),
        migrations.AddField(
            model_name='tempoffers',
            name='picture_4_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=offers.models.get_shop_offers_path, verbose_name='Picture 4 thumbnail'),
        ),
    ]
