# Generated by Django 4.1.4 on 2022-12-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_tempoffers_auth_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='all_cities',
            field=models.BooleanField(default=False, help_text='NOT USED (using city_name instead)', verbose_name='Tout le maroc ?'),
        ),
    ]
