# Generated by Django 4.1.4 on 2022-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_alter_delivery_all_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_colors', to='offers.colors', verbose_name='Product Colors'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_sizes', to='offers.sizes', verbose_name='Product Sizes'),
        ),
    ]
