# Generated by Django 4.0.2 on 2022-02-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_category', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name_category', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_en', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City EN')),
                ('city_fr', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City FR')),
                ('city_ar', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City AR')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
