# Generated by Django 4.0.3 on 2022-03-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PhoneCodes',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('phone_code', models.CharField(max_length=255, unique=True, verbose_name='Phone code')),
        #     ],
        #     options={
        #         'verbose_name': 'Phone code',
        #         'verbose_name_plural': 'Phone codes',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='authshop',
        #     name='creator',
        #     field=models.BooleanField(default=False, verbose_name='Creator ?'),
        # ),
        # migrations.AlterField(
        #     model_name='authshop',
        #     name='font_name',
        #     field=models.CharField(choices=[('L', 'Light'), ('R', 'Regular'), ('S', 'Semi-bold'), ('B', 'Black')], default='L', max_length=1, verbose_name='Font name'),
        # ),
        migrations.CreateModel(
            name='AskForCreatorLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'En attente de confirmation'), ('R', 'Rejeté'), ('C', 'Confirmé')], default='A', max_length=1, verbose_name='Status')),
                ('asked_counter', models.PositiveIntegerField(default=1, verbose_name='Fois demandé')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Création')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date mise à jour')),
                ('auth_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_shop_creator', to='auth_shop.authshop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Demande créateur',
                'verbose_name_plural': 'Demandes créateur',
            },
        ),
    ]
