# Generated by Django 4.0.3 on 2022-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_code', models.CharField(max_length=255, unique=True, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'Phone code',
                'verbose_name_plural': 'Phone codes',
            },
        ),
    ]
