# Generated by Django 4.0.3 on 2022-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0002_phonecodes_authshop_creator_alter_authshop_font_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_code', models.CharField(max_length=255, unique=True, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'Phone code',
                'verbose_name_plural': 'Phone codes',
            },
        ),
        migrations.AddField(
            model_name='authshop',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='Creator ?'),
        ),
        migrations.AlterField(
            model_name='authshop',
            name='font_name',
            field=models.CharField(choices=[('L', 'Light'), ('R', 'Regular'), ('S', 'Semi-bold'), ('B', 'Black')], default='L', max_length=1, verbose_name='Font name'),
        ),
    ]
