# Generated by Django 4.0.3 on 2022-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0002_phonecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='authshop',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='Creator ?'),
        ),
    ]
