# Generated by Django 4.0.2 on 2022-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0002_categories_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='unique_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='Unique ID'),
        ),
    ]
