# Generated by Django 4.0.2 on 2022-02-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0003_alter_tempshop_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='TempShop',
        ),
    ]
