# Generated by Django 4.0.3 on 2022-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0004_alter_authshop_font_name_askforcreatorlabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askforcreatorlabel',
            options={'verbose_name': 'Demande créateur', 'verbose_name_plural': 'Demandes créateur'},
        ),
        migrations.AlterField(
            model_name='askforcreatorlabel',
            name='asked_counter',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Fois demandé'),
        ),
    ]
