# Generated by Django 4.0.2 on 2022-02-05 17:49

import auth_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0004_delete_cities_delete_tempshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authshop',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=auth_shop.models.get_avatar_path, verbose_name='Avatar'),
        ),
    ]
