# Generated by Django 4.0.3 on 2022-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0005_alter_askforcreatorlabel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askforcreatorlabel',
            name='asked_counter',
            field=models.PositiveIntegerField(default=1, verbose_name='Fois demandé'),
        ),
        migrations.AlterField(
            model_name='askforcreatorlabel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Création'),
        ),
        migrations.AlterField(
            model_name='askforcreatorlabel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date mise à jour'),
        ),
    ]
