# Generated by Django 4.0.2 on 2022-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0005_alter_authshop_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_color', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name_color', models.CharField(max_length=255, unique=True, verbose_name='Color Name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_size', models.CharField(blank=True, default=None, max_length=2, null=True, unique=True)),
                ('name_size', models.CharField(max_length=255, unique=True, verbose_name='Size Name')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
