# Generated by Django 4.0.3 on 2022-03-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0003_phonecodes_authshop_creator_alter_authshop_font_name'),
        ('auth_shop', '0006_alter_askforcreatorlabel_asked_counter_and_more'),
    ]

    operations = [
    ]
