# Generated by Django 4.0.4 on 2022-05-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeVacance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('auth_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_shop_mode_vacance', to='auth_shop.authshop', verbose_name='Auth shop')),
            ],
            options={
                'verbose_name': 'Mode vacance',
                'verbose_name_plural': 'Mode vacances',
            },
        ),
    ]
