# Generated by Django 4.0.4 on 2022-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0002_modevacance'),
    ]

    operations = [
        migrations.AddField(
            model_name='authshop',
            name='mode_vacance_task_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Mode Vacance Task ID'),
        ),
    ]
