# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0004_deletedauthshops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askforcreatorlabel',
            options={'verbose_name': 'Demande Créateur', 'verbose_name_plural': 'Demandes Créateur'},
        ),
        migrations.AlterModelOptions(
            name='modevacance',
            options={'verbose_name': 'Mode Vacance', 'verbose_name_plural': 'Mode Vacances'},
        ),
        migrations.AlterField(
            model_name='authshop',
            name='qaryb_link',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='Qaryb link'),
        ),
    ]
