# Generated by Django 4.1 on 2022-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_tempshop_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='authshop',
            name='border',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Border'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='icon_color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Icon color'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='border',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Border'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='icon_color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Icon color'),
        ),
    ]
