# Generated by Django 4.1 on 2022-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_authshop_border_authshop_icon_color_tempshop_border_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authshop',
            name='phone_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Phone code'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='whatsapp_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Whatsapp code'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='phone_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Phone code'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='whatsapp_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Whatsapp code'),
        ),
    ]
