# Generated by Django 4.1 on 2022-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_authshop_phone_code_authshop_whatsapp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authshop',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='authshop',
            name='whatsapp_code',
        ),
        migrations.RemoveField(
            model_name='tempshop',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='tempshop',
            name='whatsapp_code',
        ),
        migrations.AddField(
            model_name='authshop',
            name='contact_mode',
            field=models.CharField(choices=[('', 'Unset'), ('P', 'Phone'), ('W', 'Whatsapp')], default='', max_length=1, verbose_name='Contact mode'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Contact phone number'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='contact_phone_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact phone code'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact whatsapp number'),
        ),
        migrations.AddField(
            model_name='authshop',
            name='contact_whatsapp_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact whatsapp code'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='contact_mode',
            field=models.CharField(choices=[('', 'Unset'), ('P', 'Phone'), ('W', 'Whatsapp')], default='', max_length=1, verbose_name='Contact mode'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Contact phone number'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='contact_phone_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact phone code'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact whatsapp number'),
        ),
        migrations.AddField(
            model_name='tempshop',
            name='contact_whatsapp_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Contact whatsapp code'),
        ),
    ]
