# Generated by Django 4.1 on 2022-08-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_authshop_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authshop',
            name='contact_mode',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('P', 'Phone'), ('W', 'Whatsapp')], default='', max_length=1, null=True, verbose_name='Contact mode'),
        ),
    ]
