# Generated by Django 4.1 on 2022-08-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_authshop_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='contact_mode',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('P', 'Phone'), ('W', 'Whatsapp')], default='', max_length=1, null=True, verbose_name='Contact mode'),
        ),
    ]
