# Generated by Django 4.1 on 2022-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_tempshop_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authshop',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Contact whatsapp number'),
        ),
        migrations.AlterField(
            model_name='tempshop',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Contact whatsapp number'),
        ),
    ]
