# Generated by Django 4.1 on 2022-08-21 16:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_authshop_contact_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authshop',
            name='bg_color_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Bg Color code'),
        ),
        migrations.AlterField(
            model_name='tempshop',
            name='bg_color_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Bg Color code'),
        ),
    ]
