# Generated by Django 4.1 on 2022-08-23 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_authshop_bg_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='latitude',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,6})?))$', 'Only Geo numbers are allowed.')], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='tempshop',
            name='longitude',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,6})?))$', 'Only Geo numbers are allowed.')], verbose_name='Longitude'),
        ),
    ]
