# Generated by Django 4.1.5 on 2023-01-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_authshop_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authshop',
            options={'ordering': ('-created_date',), 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
    ]
