# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempshop',
            name='qaryb_link',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='Qaryb link'),
        ),
    ]
