# Generated by Django 4.0.2 on 2022-02-07 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import temp_product.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('temp_shop', '0001_initial'),
        ('auth_shop', '0005_alter_authshop_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('V', 'Sell'), ('S', 'Service'), ('L', 'Location')], max_length=1, verbose_name='Product Type')),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('picture_1', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 1')),
                ('picture_2', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 2')),
                ('picture_3', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 3')),
                ('picture_4', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 4')),
                ('picture_1_thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 1 thumbnail')),
                ('picture_2_thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 2 thumbnail')),
                ('picture_3_thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 3 thumbnail')),
                ('picture_4_thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to=temp_product.base.models.get_shop_products_path, verbose_name='Picture 4 thumbnail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('for_whom', models.CharField(choices=[('A', 'All'), ('K', 'Kid'), ('F', 'Female'), ('M', 'Man')], max_length=1, verbose_name='For Whom')),
                ('product_color', models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('BR', 'Brown'), ('BL', 'Blue'), ('GN', 'Green'), ('PR', 'Purple'), ('OR', 'Orange'), ('PI', 'Pink'), ('YE', 'Yellow'), ('GR', 'Gray'), ('MC', 'MultiColor'), ('RD', 'Red')], max_length=2, verbose_name='Product Color')),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'XLarge')], max_length=1, verbose_name='Product Size')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('price_by', models.CharField(choices=[('U', 'Unity'), ('K', 'Kilogram'), ('L', 'Liter')], max_length=1, verbose_name='Price by')),
                ('shop_longitude', models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,6})?))$', 'Only Geo numbers are allowed.')], verbose_name='Shop Longitude')),
                ('shop_latitude', models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,6})?))$', 'Only Geo numbers are allowed.')], verbose_name='Shop Latitude')),
                ('shop_address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Shop Address')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product_category', models.ManyToManyField(to='auth_shop.Categories', verbose_name='Product Categories')),
                ('temp_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_shop', to='temp_shop.tempshop', verbose_name='Temp Shop')),
            ],
            options={
                'verbose_name': 'Temp Product',
                'verbose_name_plural': 'Temp Products',
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='TempDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_delivery_price', models.PositiveIntegerField(default=0, verbose_name='Temp delivery Price')),
                ('temp_delivery_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_delivery_city', to='places.cities', verbose_name='Temp Delivery City')),
                ('temp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_delivery_temp_product', to='temp_product.tempproduct', verbose_name='Temp product')),
            ],
            options={
                'verbose_name': 'Temp Delivery',
                'verbose_name_plural': 'Temp Deliveries',
            },
        ),
    ]
