# Generated by Django 4.0.2 on 2022-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0005_alter_authshop_avatar'),
        ('temp_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempproduct',
            name='product_category',
            field=models.ManyToManyField(related_name='temp_product_categories', to='auth_shop.Categories', verbose_name='Product Categories'),
        ),
    ]
