# Generated by Django 4.0.2 on 2022-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_product', '0002_alter_tempproduct_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdelivery',
            name='temp_delivery_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Temp number of Days'),
        ),
    ]
