# Generated by Django 4.0.2 on 2022-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0006_colors_sizes'),
        ('temp_product', '0003_tempdelivery_temp_delivery_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempproduct',
            name='product_color',
        ),
        migrations.AddField(
            model_name='tempproduct',
            name='product_color',
            field=models.ManyToManyField(related_name='temp_product_colors', to='auth_shop.Colors', verbose_name='Product Colors'),
        ),
        migrations.RemoveField(
            model_name='tempproduct',
            name='product_size',
        ),
        migrations.AddField(
            model_name='tempproduct',
            name='product_size',
            field=models.ManyToManyField(related_name='temp_product_sizes', to='auth_shop.Sizes', verbose_name='Product Sizes'),
        ),
    ]
