# Generated by Django 4.0.2 on 2022-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('temp_product', '0004_remove_tempproduct_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_city',
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='temp_delivery_city',
            field=models.ManyToManyField(related_name='temp_delivery_city', to='places.Cities', verbose_name='Temp Delivery City'),
        ),
    ]
