# Generated by Django 4.0.2 on 2022-02-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_product', '0006_remove_tempproduct_for_whom_tempproduct_for_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempproduct',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='TempSolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_solder_type', models.CharField(choices=[('F', 'Prix fix'), ('P', 'Pourcentage')], max_length=1, verbose_name='Temp solder type')),
                ('temp_solder_value', models.FloatField(default=0.0, verbose_name='Temp solder value')),
                ('temp_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_product_solder', to='temp_product.tempproduct', verbose_name='Temp product')),
            ],
        ),
    ]
