# Generated by Django 4.0.5 on 2022-06-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_color', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Picked Color')),
                ('picked_size', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Picked Size')),
                ('picked_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('picked_date', models.DateField(blank=True, default=None, null=True, verbose_name='Picked Date')),
                ('picked_hour', models.TimeField(blank=True, default=None, null=True, verbose_name='Picked Hour')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_offer', to='offers.offers', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-created_date', '-updated_date'),
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
