# Generated by Django 4.0.3 on 2022-04-01 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_color', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Picked Color')),
                ('picked_size', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Picked Size')),
                ('note', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Note')),
                ('picked_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_user', to='offer.offers', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-pk',),
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
