# Generated by Django 4.1.4 on 2022-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_tempoffers_auth_shop_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='unique_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Cart unique ID'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('unique_id', 'offer')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
