# Generated by Django 4.0.4 on 2022-05-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_vues', to='offer.offers', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Offer Vue',
                'verbose_name_plural': 'Offers Vues',
            },
        ),
        migrations.DeleteModel(
            name='OffersVue',
        ),
    ]
