# Generated by Django 4.0.4 on 2022-05-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offervue_delete_offersvue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offervue',
            name='date',
        ),
        migrations.AddField(
            model_name='offervue',
            name='nbr_total_vue',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbr Total Vue'),
        ),
        migrations.AlterField(
            model_name='offervue',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_vues', to='offer.offers', verbose_name='Offer'),
        ),
        migrations.CreateModel(
            name='OffersTotalVues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, choices=[('1', 'Janvier'), ('2', 'Février'), ('3', 'Mars'), ('4', 'Avril'), ('5', 'Mai'), ('6', 'Juin'), ('7', 'Juillet'), ('8', 'Août'), ('9', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], default=None, max_length=2, null=True, verbose_name='Date')),
                ('nbr_total_vue', models.PositiveIntegerField(default=0, verbose_name='Nbr Total Vue')),
                ('offer_vue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_total_vues', to='offer.offers', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Offer Total Vue',
                'verbose_name_plural': 'Offers Total Vues',
            },
        ),
    ]
