# Generated by Django 4.0.4 on 2022-05-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
        ('offer', '0004_rename_offer_vue_offerstotalvues_offer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerstotalvues',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offerstotalvues',
            name='auth_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authshop_total_vues', to='auth_shop.authshop', verbose_name='AuthShop'),
        ),
        migrations.AlterUniqueTogether(
            name='offerstotalvues',
            unique_together={('auth_shop', 'date')},
        ),
        migrations.RemoveField(
            model_name='offerstotalvues',
            name='offer',
        ),
    ]
