# Generated by Django 4.0.4 on 2022-05-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_shop', '0001_initial'),
        ('offer', '0005_alter_offerstotalvues_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerstotalvues',
            name='auth_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authshop_total_vues', to='auth_shop.authshop', verbose_name='AuthShop'),
        ),
    ]
