# Generated by Django 4.0.4 on 2022-05-10 13:58

from django.db import migrations, models
import django.db.models.deletion
import offer.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_offerstotalvues_auth_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='offervue',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=offer.base.models.get_fallback_shop_offers_path, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='offervue',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='offervue',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_vues', to='offer.offers', verbose_name='Offer'),
        ),
    ]
