# Generated by Django 4.0.5 on 2022-06-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Global version')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Maintenance')),
            ],
            options={
                'verbose_name_plural': 'Version',
            },
        ),
    ]
