# Generated by Django 4.1.2 on 2022-10-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('domiciliation', models.CharField(max_length=255, verbose_name='Domiciliation')),
                ('numero_de_compte', models.CharField(max_length=255, verbose_name='N° de compte')),
                ('titulaire_du_compte', models.CharField(max_length=255, verbose_name='Titulaire du compte')),
                ('numero_rib', models.CharField(max_length=255, verbose_name='N° du RIB')),
                ('identifiant_swift', models.CharField(max_length=255, verbose_name='Identifiant SWIFT')),
            ],
            options={
                'verbose_name': 'Virement admin data',
                'verbose_name_plural': 'Virement admin data',
                'ordering': ('-pk',),
            },
        ),
    ]
