# Generated by Django 4.1.2 on 2022-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_virementdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'News letter',
                'verbose_name_plural': 'News letters',
                'ordering': ('-pk',),
            },
        ),
    ]
