# Generated by Django 4.0.2 on 2022-02-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempservices',
            options={'ordering': ('-pk',), 'verbose_name': 'Temp Service', 'verbose_name_plural': 'Temp Services'},
        ),
    ]
