# Generated by Django 4.0.3 on 2022-03-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('temp_offer', '0003_alter_tempproducts_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_city_1',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_city_2',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_city_3',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_days_1',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_days_2',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_days_3',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_price_1',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_price_2',
        ),
        migrations.RemoveField(
            model_name='tempdelivery',
            name='temp_delivery_price_3',
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='temp_delivery_city',
            field=models.ManyToManyField(related_name='temp_delivery_city', to='places.city', verbose_name='Temp Delivery City'),
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='temp_delivery_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Temp number of Days'),
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='temp_delivery_price',
            field=models.FloatField(default=0.0, verbose_name='Temp delivery Price'),
        ),
        migrations.AlterField(
            model_name='tempdelivery',
            name='temp_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_offer_delivery', to='temp_offer.tempoffers', verbose_name='Temp Offer'),
        ),
    ]
