# Generated by Django 4.0.3 on 2022-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_offertags_offers_creator_label_offers_made_in_label_and_more'),
        ('temp_offer', '0004_remove_tempdelivery_temp_delivery_city_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempoffers',
            name='tags',
            field=models.ManyToManyField(related_name='temp_offer_tags', to='offer.offertags', verbose_name='Temp Offer Tags'),
        ),
        migrations.AlterField(
            model_name='tempoffers',
            name='for_whom',
            field=models.ManyToManyField(related_name='temp_offer_for_whom', to='offer.forwhom', verbose_name='For Whom'),
        ),
    ]
