# Generated by Django 4.1.5 on 2023-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notifications_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('SA', 'Subscription activated'), ('OR', 'Order received'), ('OA', 'Order accepted'), ('CS', 'Order cancelled by the seller'), ('CB', 'Order cancelled by the buyer')], default='', max_length=2, null=True),
        ),
    ]
