# Generated by Django 4.1.6 on 2023-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notifications_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('SA', 'Subscription activated'), ('OR', 'Order received'), ('OA', 'Order accepted'), ('CA', 'Order cancelled')], default='', max_length=2, null=True),
        ),
    ]
