# Generated by Django 4.0.6 on 2022-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='highest_delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='offer_canceled',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('TC', 'To confirm'), ('OG', 'On-going'), ('SH', 'Shipped'), ('RD', 'Ready'), ('TE', 'To evaluate'), ('CM', 'Completed'), ('CB', 'Canceled by buyer'), ('CS', 'Canceled by seller')], default='TC', max_length=2, verbose_name='Order Status'),
        ),
    ]
