# Generated by Django 4.0.6 on 2022-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_highest_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='highest_delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Highest delivery price'),
        ),
    ]
