# Generated by Django 4.0.6 on 2022-07-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_temp_delivery_city_tempdelivery_delivery_city_and_more'),
        ('order', '0003_order_highest_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='new_delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='New Delivery price'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='new_delivery_price_body',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='New delivery price body'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='new_delivery_price_reason',
            field=models.CharField(blank=True, choices=[('P', 'Weight is greater'), ('O', 'Other'), ('', 'Unset')], default='', max_length=1, null=True, verbose_name='New delivery price reason'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details_offer', to='offers.offers', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='seller_cancel_body',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Seller cancel body'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='seller_canceled_reason',
            field=models.CharField(blank=True, choices=[('S', 'No more stock'), ('I', 'Not available'), ('O', 'Other'), ('', 'Unset')], default='', max_length=1, null=True, verbose_name='Seller canceled'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('TC', 'To confirm'), ('DP', 'Delivery price'), ('OG', 'On-going'), ('SH', 'Shipped'), ('RD', 'Ready'), ('TE', 'To evaluate'), ('CM', 'Completed'), ('CB', 'Canceled by buyer'), ('CS', 'Canceled by seller')], default='TC', max_length=2, verbose_name='Order Status'),
        ),
    ]
