# Generated by Django 4.1 on 2022-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetails_new_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='has_buyer_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='has_seller_rating',
            field=models.BooleanField(default=False),
        ),
    ]
