# Generated by Django 4.1 on 2022-08-23 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderdetails_has_buyer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_latitude',
            field=models.FloatField(default=False, max_length=10, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product latitude'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_longitude',
            field=models.FloatField(default=False, max_length=10, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product longitude'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='service_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Latitude'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='service_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Service Longitude'),
        ),
    ]
