# Generated by Django 4.1.4 on 2022-12-16 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_authshop_facebook_link_and_more'),
        ('order', '0007_alter_orderdetails_picked_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='title',
            new_name='offer_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='highest_delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_avatar_thumbnail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='viewed_buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='viewed_seller',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='has_buyer_rating',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='has_seller_rating',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='new_delivery_price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='new_delivery_price_body',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='new_delivery_price_reason',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='seller_cancel_body',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='seller_canceled_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CM', 'Completed'), ('CA', 'Canceled')], default='IP', max_length=2, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_delivery_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Delivery price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Order total price'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='offer_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_avatar_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=order.models.get_buyer_avatar_path, verbose_name='Buyer Thumb Avatar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_for_auth_shop', to='shop.authshop'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='delivery_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Delivery price'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='offer_type',
            field=models.CharField(choices=[('V', 'Sell'), ('S', 'Service'), ('L', 'Location')], default='V', max_length=1, verbose_name='Offer Type'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='picked_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='product_address'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_latitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:90(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product latitude'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_longitude',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\+|-)?(?:180(?:(?:\\.0{1,18})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,18})?))$', 'Only Geo numbers are allowed.')], verbose_name='Product longitude'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Zip code'),
        ),
    ]
