# Generated by Django 4.1.4 on 2022-12-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderdetails_total_self_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='offer',
        ),
    ]
