# Generated by Django 4.1.4 on 2022-12-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_alter_products_product_colors_and_more'),
        ('order', '0011_remove_orderdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details_offer', to='offers.offers', verbose_name='Offer'),
        ),
    ]
