# Generated by Django 4.1.4 on 2022-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderdetails_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='service_km_radius',
            field=models.FloatField(blank=True, default=13, null=True, verbose_name='Km radius'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='service_zone_by',
            field=models.CharField(blank=True, choices=[('A', 'Address'), ('S', 'Sector')], default=None, max_length=1, null=True, verbose_name='Zone by'),
        ),
    ]
