# Generated by Django 4.1.5 on 2023-01-10 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_authshop_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0014_rename_total_delivery_price_order_highest_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer_order', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_for_auth_shop', to='shop.authshop', verbose_name='Seller'),
        ),
    ]
