# Generated by Django 4.1.5 on 2023-01-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_buyer_alter_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CM', 'Completed'), ('CB', 'Canceled by the buyer'), ('CS', 'Canceled by the seller')], default='IP', max_length=2, verbose_name='Order Status'),
        ),
    ]
