# Generated by Django 4.1.5 on 2023-01-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CM', 'Completed'), ('CA', 'Canceled')], default='IP', max_length=2, verbose_name='Order Status'),
        ),
    ]
